-- Script para crear catálogo de cuentas contables
-- Ejecutar en Supabase SQL Editor

-- Eliminar tabla si existe
DROP TABLE IF EXISTS cuentas_contables CASCADE;

-- Crear tabla de cuentas contables
CREATE TABLE cuentas_contables (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL,
  nombre VARCHAR(500) NOT NULL,
  empresa VARCHAR(20) NOT NULL CHECK (empresa IN ('BUZZWORD', 'INOVITZ')),
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear índice compuesto para búsquedas eficientes
CREATE INDEX idx_cuentas_contables_codigo ON cuentas_contables(codigo);
CREATE INDEX idx_cuentas_contables_empresa ON cuentas_contables(empresa);
CREATE INDEX idx_cuentas_contables_empresa_codigo ON cuentas_contables(empresa, codigo);

-- Insertar cuentas contables de BUZZWORD (ejemplo - reemplazar con datos reales del Excel)
INSERT INTO cuentas_contables (codigo, nombre, empresa) VALUES
('1000', 'EFECTIVO Y EQUIVALENTES', 'BUZZWORD'),
('1001', 'CAJA GENERAL', 'BUZZWORD'),
('1002', 'BANCOS NACIONALES', 'BUZZWORD'),
('1003', 'BANCOS EXTRANJEROS', 'BUZZWORD'),
('1100', 'INVERSIONES TEMPORALES', 'BUZZWORD'),
('1200', 'CUENTAS POR COBRAR', 'BUZZWORD'),
('1201', 'CLIENTES NACIONALES', 'BUZZWORD'),
('1202', 'CLIENTES EXTRANJEROS', 'BUZZWORD'),
('1203', 'DOCUMENTOS POR COBRAR', 'BUZZWORD'),
('1300', 'INVENTARIOS', 'BUZZWORD'),
('1400', 'GASTOS PAGADOS POR ANTICIPADO', 'BUZZWORD'),
('1500', 'INMUEBLES, PLANTA Y EQUIPO', 'BUZZWORD'),
('1501', 'TERRENOS', 'BUZZWORD'),
('1502', 'EDIFICIOS', 'BUZZWORD'),
('1503', 'MAQUINARIA Y EQUIPO', 'BUZZWORD'),
('1504', 'EQUIPO DE COMPUTO', 'BUZZWORD'),
('1505', 'MUEBLES Y ENSERES', 'BUZZWORD'),
('1506', 'EQUIPO DE TRANSPORTE', 'BUZZWORD'),
('1600', 'ACTIVOS INTANGIBLES', 'BUZZWORD'),
('1601', 'SOFTWARE', 'BUZZWORD'),
('1602', 'MARCAS Y PATENTES', 'BUZZWORD'),
('1603', 'GASTOS DE CONSTITUCIÓN', 'BUZZWORD'),
('2000', 'PASIVOS A CORTO PLAZO', 'BUZZWORD'),
('2001', 'PROVEEDORES NACIONALES', 'BUZZWORD'),
('2002', 'PROVEEDORES EXTRANJEROS', 'BUZZWORD'),
('2003', 'DOCUMENTOS POR PAGAR', 'BUZZWORD'),
('2004', 'ACREEDORES DIVERSOS', 'BUZZWORD'),
('2005', 'GASTOS ACUMULADOS', 'BUZZWORD'),
('2006', 'IMPUESTOS POR PAGAR', 'BUZZWORD'),
('2007', 'NÓMINA POR PAGAR', 'BUZZWORD'),
('2008', 'PRESTACIONES LABORALES', 'BUZZWORD'),
('3000', 'PASIVOS A LARGO PLAZO', 'BUZZWORD'),
('3001', 'CRÉDITOS BANCARIOS LARGO PLAZO', 'BUZZWORD'),
('3002', 'DOCUMENTOS POR PAGAR LARGO PLAZO', 'BUZZWORD'),
('4000', 'CAPITAL CONTABLE', 'BUZZWORD'),
('4001', 'CAPITAL SOCIAL', 'BUZZWORD'),
('4002', 'RESERVA LEGAL', 'BUZZWORD'),
('4003', 'UTILIDADES ACUMULADAS', 'BUZZWORD'),
('4004', 'RESULTADO DEL EJERCICIO', 'BUZZWORD'),
('5000', 'INGRESOS', 'BUZZWORD'),
('5001', 'VENTAS NACIONALES', 'BUZZWORD'),
('5002', 'VENTAS DE EXPORTACIÓN', 'BUZZWORD'),
('5003', 'SERVICIOS PRESTADOS', 'BUZZWORD'),
('5004', 'OTROS INGRESOS', 'BUZZWORD'),
('6000', 'COSTOS DE VENTAS', 'BUZZWORD'),
('6001', 'COSTO DE VENTAS NACIONALES', 'BUZZWORD'),
('6002', 'COSTO DE VENTAS DE EXPORTACIÓN', 'BUZZWORD'),
('6003', 'COSTO DE SERVICIOS', 'BUZZWORD'),
('7000', 'GASTOS DE OPERACIÓN', 'BUZZWORD'),
('7001', 'GASTOS DE VENTAS', 'BUZZWORD'),
('7002', 'GASTOS DE ADMINISTRACIÓN', 'BUZZWORD'),
('7003', 'GASTOS FINANCIEROS', 'BUZZWORD'),
('8000', 'OTROS INGRESOS Y GASTOS', 'BUZZWORD'),
('8001', 'PRODUCTOS FINANCIEROS', 'BUZZWORD'),
('8002', 'OTROS PRODUCTOS', 'BUZZWORD'),
('8003', 'OTROS GASTOS', 'BUZZWORD');

-- Insertar cuentas contables de INOVITZ (ejemplo - reemplazar con datos reales del Excel)
INSERT INTO cuentas_contables (codigo, nombre, empresa) VALUES
('1000', 'EFECTIVO Y EQUIVALENTES', 'INOVITZ'),
('1001', 'CAJA GENERAL', 'INOVITZ'),
('1002', 'BANCOS NACIONALES', 'INOVITZ'),
('1003', 'BANCOS EXTRANJEROS', 'INOVITZ'),
('1100', 'INVERSIONES TEMPORALES', 'INOVITZ'),
('1200', 'CUENTAS POR COBRAR', 'INOVITZ'),
('1201', 'CLIENTES NACIONALES', 'INOVITZ'),
('1202', 'CLIENTES EXTRANJEROS', 'INOVITZ'),
('1203', 'DOCUMENTOS POR COBRAR', 'INOVITZ'),
('1300', 'INVENTARIOS', 'INOVITZ'),
('1400', 'GASTOS PAGADOS POR ANTICIPADO', 'INOVITZ'),
('1500', 'INMUEBLES, PLANTA Y EQUIPO', 'INOVITZ'),
('1501', 'TERRENOS', 'INOVITZ'),
('1502', 'EDIFICIOS', 'INOVITZ'),
('1503', 'MAQUINARIA Y EQUIPO', 'INOVITZ'),
('1504', 'EQUIPO DE COMPUTO', 'INOVITZ'),
('1505', 'MUEBLES Y ENSERES', 'INOVITZ'),
('1506', 'EQUIPO DE TRANSPORTE', 'INOVITZ'),
('1600', 'ACTIVOS INTANGIBLES', 'INOVITZ'),
('1601', 'SOFTWARE', 'INOVITZ'),
('1602', 'MARCAS Y PATENTES', 'INOVITZ'),
('1603', 'GASTOS DE CONSTITUCIÓN', 'INOVITZ'),
('2000', 'PASIVOS A CORTO PLAZO', 'INOVITZ'),
('2001', 'PROVEEDORES NACIONALES', 'INOVITZ'),
('2002', 'PROVEEDORES EXTRANJEROS', 'INOVITZ'),
('2003', 'DOCUMENTOS POR PAGAR', 'INOVITZ'),
('2004', 'ACREEDORES DIVERSOS', 'INOVITZ'),
('2005', 'GASTOS ACUMULADOS', 'INOVITZ'),
('2006', 'IMPUESTOS POR PAGAR', 'INOVITZ'),
('2007', 'NÓMINA POR PAGAR', 'INOVITZ'),
('2008', 'PRESTACIONES LABORALES', 'INOVITZ'),
('3000', 'PASIVOS A LARGO PLAZO', 'INOVITZ'),
('3001', 'CRÉDITOS BANCARIOS LARGO PLAZO', 'INOVITZ'),
('3002', 'DOCUMENTOS POR PAGAR LARGO PLAZO', 'INOVITZ'),
('4000', 'CAPITAL CONTABLE', 'INOVITZ'),
('4001', 'CAPITAL SOCIAL', 'INOVITZ'),
('4002', 'RESERVA LEGAL', 'INOVITZ'),
('4003', 'UTILIDADES ACUMULADAS', 'INOVITZ'),
('4004', 'RESULTADO DEL EJERCICIO', 'INOVITZ'),
('5000', 'INGRESOS', 'INOVITZ'),
('5001', 'VENTAS NACIONALES', 'INOVITZ'),
('5002', 'VENTAS DE EXPORTACIÓN', 'INOVITZ'),
('5003', 'SERVICIOS PRESTADOS', 'INOVITZ'),
('5004', 'OTROS INGRESOS', 'INOVITZ'),
('6000', 'COSTOS DE VENTAS', 'INOVITZ'),
('6001', 'COSTO DE VENTAS NACIONALES', 'INOVITZ'),
('6002', 'COSTO DE VENTAS DE EXPORTACIÓN', 'INOVITZ'),
('6003', 'COSTO DE SERVICIOS', 'INOVITZ'),
('7000', 'GASTOS DE OPERACIÓN', 'INOVITZ'),
('7001', 'GASTOS DE VENTAS', 'INOVITZ'),
('7002', 'GASTOS DE ADMINISTRACIÓN', 'INOVITZ'),
('7003', 'GASTOS FINANCIEROS', 'INOVITZ'),
('8000', 'OTROS INGRESOS Y GASTOS', 'INOVITZ'),
('8001', 'PRODUCTOS FINANCIEROS', 'INOVITZ'),
('8002', 'OTROS PRODUCTOS', 'INOVITZ'),
('8003', 'OTROS GASTOS', 'INOVITZ');

-- Verificar datos insertados
SELECT 'Cuentas Contables' as tabla, COUNT(*) as total FROM cuentas_contables;
SELECT 'Por Empresa:' as info;
SELECT empresa, COUNT(*) as total FROM cuentas_contables GROUP BY empresa;

-- Mostrar algunas cuentas de ejemplo
SELECT 'BUZZWORD - Primeras 10 cuentas:' as info;
SELECT codigo, nombre FROM cuentas_contables WHERE empresa = 'BUZZWORD' ORDER BY codigo LIMIT 10;

SELECT 'INOVITZ - Primeras 10 cuentas:' as info;
SELECT codigo, nombre FROM cuentas_contables WHERE empresa = 'INOVITZ' ORDER BY codigo LIMIT 10;
